### ISSUE TITLE
Never use > as a prompt

### ISSUE THREAD

**Issue by voederbietel** [liljencrantz/crush#12]
Ancient sysadmin wisdom: don’t use ‘>’ as part of your shell prompt. You’re one copy/paste error away from truncating a file. 

There’s a reason root’s ‘#’ prompt gets interpreted as a comment.
https://twitter.com/QuinnyPig/status/1291411065608208384?s=20

Can the default prompt be changed?

**Comment by liljencrantz** [comment]
I absolutely see what you're saying in normal shell languages that uses < and > for IO redirection, but since crush generally uses *typed* data, you use commands like `json:from my_file.josn` to read files. The < and > symbols are the comparison operators in Crush.

There is still some benefit to making copy-and-paste with a prompt automatically make things a comment though.

**Comment by liljencrantz** [comment]
Fixed in https://github.com/liljencrantz/crush/commit/9d417582ec23d33b64aa2180028b5718b7ca6606

**Comment by voederbietel** [comment]
Thanks for the quick fix
